# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on: [workflow_dispatch]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
      
          # Options
          user: sinadalvand
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Tehran
          plugin_followup: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_projects: yes
          plugin_projects_limit: 6
          plugin_stars: yes
          plugin_stars_limit: 4
